# Generated by Django 5.2.8 on 2025-11-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bukti_foto', models.ImageField(upload_to='pelanggar/')),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('lokasi', models.CharField(default='-', max_length=255)),
            ],
        ),
    ]
