# Generated by Django 5.2.8 on 2025-11-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='jenis',
            field=models.CharField(default='Tidak Pakai Helm', max_length=100),
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='bukti_foto',
            field=models.ImageField(blank=True, null=True, upload_to='pelanggar/'),
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='waktu',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
